#!/bin/bash
##SBATCH --partition=C1Mitad1
#SBATCH --partition=GPU
#SBATCH --job-name=Vae_CAT
#SBATCH --output=results.log
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=giovanni.lopez@cimat.mx
cd /home/est_posgrado_giovanni.lopez/Maquina_II/Tarea_02/Scripts
source /opt/anaconda3_titan/bin/activate
conda activate tensorflow
export TF_ENABLE_ONEDNN_OPTS=0
hostname
date
#python train_VAE.py dog
#python test_VAE.py dog
python train_VAE.py cat
python test_VAE.py cat
#python train.py
date
